#############################################################################
# Makefile for building: jake++
# Generated by qmake (2.01a) (Qt 4.8.3) on: lun oct 8 21:21:51 2012
# Project:  jake++.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile jake++.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/phonon -I/usr/include -I/usr/include/QtTest -I/usr/X11R6/include -I/usr/include/phonon_compat -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/X11R6/lib64 -L/usr/lib -lQtTest -lphonon -lQtGui -lQtNetwork -lQtCore -lpthread -lXext -lX11 -lm
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qconsole.cpp \
		qcustomtabbar.cpp \
		qcustomtabwidget.cpp \
		qcustomtextbrowser.cpp \
		libs/qtnam/syncdown.cpp \
		libs/qtnam/asyncdown.cpp \
		qcustompluginmanager.cpp \
		qcustomtabbarlineedit.cpp \
		utils/qtplayer/qtplayer.cpp \
		libs/qtglobalshortcut/qtglobal.cpp \
		plugins/test/qcustomplugintest.cpp \
		plugins/music-goear/music-goear.cpp \
		libs/qtglobalshortcut/qtglobalshortcut.cpp \
		libs/qtsingleapplication/qtsingleapplication.cpp \
		libs/qtsingleapplication/qtlocalpeer.cpp \
		libs/qtgoear/qtgoear.cpp \
		libs/qtglobalshortcut/qtglobalshortcut_x11.cpp moc_qconsole.cpp \
		moc_qcustomtabbar.cpp \
		moc_qcustomplugin.cpp \
		moc_qcustomtabwidget.cpp \
		moc_qcustomtextbrowser.cpp \
		moc_syncdown.cpp \
		moc_asyncdown.cpp \
		moc_qcustompluginmanager.cpp \
		moc_qcustomtabbarlineedit.cpp \
		moc_qtplayer.cpp \
		moc_qcustomplugintest.cpp \
		moc_music-goear.cpp \
		moc_qtglobalshortcut.cpp \
		moc_qtsingleapplication.cpp \
		moc_qtlocalpeer.cpp \
		moc_qtgoear.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		qconsole.o \
		qcustomtabbar.o \
		qcustomtabwidget.o \
		qcustomtextbrowser.o \
		syncdown.o \
		asyncdown.o \
		qcustompluginmanager.o \
		qcustomtabbarlineedit.o \
		qtplayer.o \
		qtglobal.o \
		qcustomplugintest.o \
		music-goear.o \
		qtglobalshortcut.o \
		qtsingleapplication.o \
		qtlocalpeer.o \
		qtgoear.o \
		qtglobalshortcut_x11.o \
		moc_qconsole.o \
		moc_qcustomtabbar.o \
		moc_qcustomplugin.o \
		moc_qcustomtabwidget.o \
		moc_qcustomtextbrowser.o \
		moc_syncdown.o \
		moc_asyncdown.o \
		moc_qcustompluginmanager.o \
		moc_qcustomtabbarlineedit.o \
		moc_qtplayer.o \
		moc_qcustomplugintest.o \
		moc_music-goear.o \
		moc_qtglobalshortcut.o \
		moc_qtsingleapplication.o \
		moc_qtlocalpeer.o \
		moc_qtgoear.o \
		qrc_resources.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/x11.prf \
		/usr/share/qt/mkspecs/features/unix/x11inc.prf \
		/usr/share/qt/mkspecs/features/unix/x11lib.prf \
		/usr/share/qt/mkspecs/features/qtestlib.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		jake++.pro
QMAKE_TARGET  = jake++
DESTDIR       = 
TARGET        = jake++

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: jake++.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/x11.prf \
		/usr/share/qt/mkspecs/features/unix/x11inc.prf \
		/usr/share/qt/mkspecs/features/unix/x11lib.prf \
		/usr/share/qt/mkspecs/features/qtestlib.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtTest.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile jake++.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/x11.prf:
/usr/share/qt/mkspecs/features/unix/x11inc.prf:
/usr/share/qt/mkspecs/features/unix/x11lib.prf:
/usr/share/qt/mkspecs/features/qtestlib.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtTest.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile jake++.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/jake++1.0.0 || $(MKDIR) .tmp/jake++1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/jake++1.0.0/ && $(COPY_FILE) --parents qconsole.h qcustomtabbar.h qcustomplugin.h qcustomtabwidget.h qcustomtextbrowser.h libs/qtnam/syncdown.h libs/qtnam/asyncdown.h qcustompluginmanager.h qcustomtabbarlineedit.h utils/qtplayer/qtplayer.h plugins/test/qcustomplugintest.h libs/qtglobalshortcut/qtglobal.h plugins/music-goear/music-goear.h libs/qtglobalshortcut/qtglobalshortcut.h libs/qtglobalshortcut/qtglobalshortcut_p.h libs/qtsingleapplication/qtsingleapplication.h libs/qtsingleapplication/qtlocalpeer.h libs/qtsingleapplication/qtlockedfile.h libs/qtgoear/qtgoear.h .tmp/jake++1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/jake++1.0.0/ && $(COPY_FILE) --parents main.cpp qconsole.cpp qcustomtabbar.cpp qcustomtabwidget.cpp qcustomtextbrowser.cpp libs/qtnam/syncdown.cpp libs/qtnam/asyncdown.cpp qcustompluginmanager.cpp qcustomtabbarlineedit.cpp utils/qtplayer/qtplayer.cpp libs/qtglobalshortcut/qtglobal.cpp plugins/test/qcustomplugintest.cpp plugins/music-goear/music-goear.cpp libs/qtglobalshortcut/qtglobalshortcut.cpp libs/qtsingleapplication/qtsingleapplication.cpp libs/qtsingleapplication/qtlocalpeer.cpp libs/qtgoear/qtgoear.cpp libs/qtglobalshortcut/qtglobalshortcut_x11.cpp .tmp/jake++1.0.0/ && (cd `dirname .tmp/jake++1.0.0` && $(TAR) jake++1.0.0.tar jake++1.0.0 && $(COMPRESS) jake++1.0.0.tar) && $(MOVE) `dirname .tmp/jake++1.0.0`/jake++1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/jake++1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qconsole.cpp moc_qcustomtabbar.cpp moc_qcustomplugin.cpp moc_qcustomtabwidget.cpp moc_qcustomtextbrowser.cpp moc_syncdown.cpp moc_asyncdown.cpp moc_qcustompluginmanager.cpp moc_qcustomtabbarlineedit.cpp moc_qtplayer.cpp moc_qcustomplugintest.cpp moc_music-goear.cpp moc_qtglobalshortcut.cpp moc_qtsingleapplication.cpp moc_qtlocalpeer.cpp moc_qtgoear.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qconsole.cpp moc_qcustomtabbar.cpp moc_qcustomplugin.cpp moc_qcustomtabwidget.cpp moc_qcustomtextbrowser.cpp moc_syncdown.cpp moc_asyncdown.cpp moc_qcustompluginmanager.cpp moc_qcustomtabbarlineedit.cpp moc_qtplayer.cpp moc_qcustomplugintest.cpp moc_music-goear.cpp moc_qtglobalshortcut.cpp moc_qtsingleapplication.cpp moc_qtlocalpeer.cpp moc_qtgoear.cpp
moc_qconsole.cpp: qcustomtabwidget.h \
		qcustomtabbar.h \
		qcustomtabbarlineedit.h \
		qcustomtextbrowser.h \
		qcustompluginmanager.h \
		qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		utils/qtplayer/qtplayer.h \
		libs/qtnam/asyncdown.h \
		libs/qtnam/qtdownloader.h \
		libs/qtglobalshortcut/qtglobalshortcut.h \
		libs/qtglobalshortcut/qtglobal.h \
		libs/qtsingleapplication/qtsingleapplication.h \
		qconsole.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qconsole.h -o moc_qconsole.cpp

moc_qcustomtabbar.cpp: qcustomtabbarlineedit.h \
		qcustomtabbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qcustomtabbar.h -o moc_qcustomtabbar.cpp

moc_qcustomplugin.cpp: qcustomplugin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qcustomplugin.h -o moc_qcustomplugin.cpp

moc_qcustomtabwidget.cpp: qcustomtabbar.h \
		qcustomtabbarlineedit.h \
		qcustomtextbrowser.h \
		qcustompluginmanager.h \
		qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		utils/qtplayer/qtplayer.h \
		libs/qtnam/asyncdown.h \
		libs/qtnam/qtdownloader.h \
		qcustomtabwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qcustomtabwidget.h -o moc_qcustomtabwidget.cpp

moc_qcustomtextbrowser.cpp: qcustompluginmanager.h \
		qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		utils/qtplayer/qtplayer.h \
		libs/qtnam/asyncdown.h \
		libs/qtnam/qtdownloader.h \
		qcustomtextbrowser.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qcustomtextbrowser.h -o moc_qcustomtextbrowser.cpp

moc_syncdown.cpp: libs/qtnam/syncdown.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libs/qtnam/syncdown.h -o moc_syncdown.cpp

moc_asyncdown.cpp: libs/qtnam/asyncdown.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libs/qtnam/asyncdown.h -o moc_asyncdown.cpp

moc_qcustompluginmanager.cpp: qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		qcustompluginmanager.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qcustompluginmanager.h -o moc_qcustompluginmanager.cpp

moc_qcustomtabbarlineedit.cpp: qcustomtabbarlineedit.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qcustomtabbarlineedit.h -o moc_qcustomtabbarlineedit.cpp

moc_qtplayer.cpp: libs/qtnam/asyncdown.h \
		utils/qtplayer/qtplayer.h
	/usr/bin/moc $(DEFINES) $(INCPATH) utils/qtplayer/qtplayer.h -o moc_qtplayer.cpp

moc_qcustomplugintest.cpp: qcustomplugin.h \
		plugins/test/qcustomplugintest.h
	/usr/bin/moc $(DEFINES) $(INCPATH) plugins/test/qcustomplugintest.h -o moc_qcustomplugintest.cpp

moc_music-goear.cpp: qcustomplugin.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		plugins/music-goear/music-goear.h
	/usr/bin/moc $(DEFINES) $(INCPATH) plugins/music-goear/music-goear.h -o moc_music-goear.cpp

moc_qtglobalshortcut.cpp: libs/qtglobalshortcut/qtglobal.h \
		libs/qtglobalshortcut/qtglobalshortcut.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libs/qtglobalshortcut/qtglobalshortcut.h -o moc_qtglobalshortcut.cpp

moc_qtsingleapplication.cpp: libs/qtsingleapplication/qtsingleapplication.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libs/qtsingleapplication/qtsingleapplication.h -o moc_qtsingleapplication.cpp

moc_qtlocalpeer.cpp: libs/qtsingleapplication/qtlockedfile.h \
		libs/qtsingleapplication/qtlocalpeer.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libs/qtsingleapplication/qtlocalpeer.h -o moc_qtlocalpeer.cpp

moc_qtgoear.cpp: libs/qtnam/syncdown.h \
		libs/qtgoear/qtgoear.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libs/qtgoear/qtgoear.h -o moc_qtgoear.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc
	/usr/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp qconsole.h \
		qcustomtabwidget.h \
		qcustomtabbar.h \
		qcustomtabbarlineedit.h \
		qcustomtextbrowser.h \
		qcustompluginmanager.h \
		qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		utils/qtplayer/qtplayer.h \
		libs/qtnam/asyncdown.h \
		libs/qtnam/qtdownloader.h \
		libs/qtglobalshortcut/qtglobalshortcut.h \
		libs/qtglobalshortcut/qtglobal.h \
		libs/qtsingleapplication/qtsingleapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qconsole.o: qconsole.cpp qconsole.h \
		qcustomtabwidget.h \
		qcustomtabbar.h \
		qcustomtabbarlineedit.h \
		qcustomtextbrowser.h \
		qcustompluginmanager.h \
		qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		utils/qtplayer/qtplayer.h \
		libs/qtnam/asyncdown.h \
		libs/qtnam/qtdownloader.h \
		libs/qtglobalshortcut/qtglobalshortcut.h \
		libs/qtglobalshortcut/qtglobal.h \
		libs/qtsingleapplication/qtsingleapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qconsole.o qconsole.cpp

qcustomtabbar.o: qcustomtabbar.cpp qcustomtabbar.h \
		qcustomtabbarlineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomtabbar.o qcustomtabbar.cpp

qcustomtabwidget.o: qcustomtabwidget.cpp qcustomtabwidget.h \
		qcustomtabbar.h \
		qcustomtabbarlineedit.h \
		qcustomtextbrowser.h \
		qcustompluginmanager.h \
		qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		utils/qtplayer/qtplayer.h \
		libs/qtnam/asyncdown.h \
		libs/qtnam/qtdownloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomtabwidget.o qcustomtabwidget.cpp

qcustomtextbrowser.o: qcustomtextbrowser.cpp qcustomtabwidget.h \
		qcustomtabbar.h \
		qcustomtabbarlineedit.h \
		qcustomtextbrowser.h \
		qcustompluginmanager.h \
		qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h \
		utils/qtplayer/qtplayer.h \
		libs/qtnam/asyncdown.h \
		libs/qtnam/qtdownloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomtextbrowser.o qcustomtextbrowser.cpp

syncdown.o: libs/qtnam/syncdown.cpp libs/qtnam/syncdown.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syncdown.o libs/qtnam/syncdown.cpp

asyncdown.o: libs/qtnam/asyncdown.cpp libs/qtnam/asyncdown.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o asyncdown.o libs/qtnam/asyncdown.cpp

qcustompluginmanager.o: qcustompluginmanager.cpp qcustompluginmanager.h \
		qcustomplugin.h \
		plugins/test/qcustomplugintest.h \
		plugins/music-goear/music-goear.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustompluginmanager.o qcustompluginmanager.cpp

qcustomtabbarlineedit.o: qcustomtabbarlineedit.cpp qcustomtabbarlineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomtabbarlineedit.o qcustomtabbarlineedit.cpp

qtplayer.o: utils/qtplayer/qtplayer.cpp utils/qtplayer/qtplayer.h \
		libs/qtnam/asyncdown.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtplayer.o utils/qtplayer/qtplayer.cpp

qtglobal.o: libs/qtglobalshortcut/qtglobal.cpp libs/qtglobalshortcut/qtglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtglobal.o libs/qtglobalshortcut/qtglobal.cpp

qcustomplugintest.o: plugins/test/qcustomplugintest.cpp plugins/test/qcustomplugintest.h \
		qcustomplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplugintest.o plugins/test/qcustomplugintest.cpp

music-goear.o: plugins/music-goear/music-goear.cpp plugins/music-goear/music-goear.h \
		qcustomplugin.h \
		libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o music-goear.o plugins/music-goear/music-goear.cpp

qtglobalshortcut.o: libs/qtglobalshortcut/qtglobalshortcut.cpp libs/qtglobalshortcut/qtglobalshortcut.h \
		libs/qtglobalshortcut/qtglobal.h \
		libs/qtglobalshortcut/qtglobalshortcut_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtglobalshortcut.o libs/qtglobalshortcut/qtglobalshortcut.cpp

qtsingleapplication.o: libs/qtsingleapplication/qtsingleapplication.cpp libs/qtsingleapplication/qtsingleapplication.h \
		libs/qtsingleapplication/qtlocalpeer.h \
		libs/qtsingleapplication/qtlockedfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtsingleapplication.o libs/qtsingleapplication/qtsingleapplication.cpp

qtlocalpeer.o: libs/qtsingleapplication/qtlocalpeer.cpp libs/qtsingleapplication/qtlocalpeer.h \
		libs/qtsingleapplication/qtlockedfile.h \
		libs/qtsingleapplication/qtlockedfile.cpp \
		libs/qtsingleapplication/qtlockedfile_win.cpp \
		libs/qtsingleapplication/qtlockedfile_unix.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlocalpeer.o libs/qtsingleapplication/qtlocalpeer.cpp

qtgoear.o: libs/qtgoear/qtgoear.cpp libs/qtgoear/qtgoear.h \
		libs/qtnam/syncdown.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtgoear.o libs/qtgoear/qtgoear.cpp

qtglobalshortcut_x11.o: libs/qtglobalshortcut/qtglobalshortcut_x11.cpp libs/qtglobalshortcut/qtglobalshortcut_p.h \
		libs/qtglobalshortcut/qtglobalshortcut.h \
		libs/qtglobalshortcut/qtglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtglobalshortcut_x11.o libs/qtglobalshortcut/qtglobalshortcut_x11.cpp

moc_qconsole.o: moc_qconsole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qconsole.o moc_qconsole.cpp

moc_qcustomtabbar.o: moc_qcustomtabbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomtabbar.o moc_qcustomtabbar.cpp

moc_qcustomplugin.o: moc_qcustomplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplugin.o moc_qcustomplugin.cpp

moc_qcustomtabwidget.o: moc_qcustomtabwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomtabwidget.o moc_qcustomtabwidget.cpp

moc_qcustomtextbrowser.o: moc_qcustomtextbrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomtextbrowser.o moc_qcustomtextbrowser.cpp

moc_syncdown.o: moc_syncdown.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_syncdown.o moc_syncdown.cpp

moc_asyncdown.o: moc_asyncdown.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_asyncdown.o moc_asyncdown.cpp

moc_qcustompluginmanager.o: moc_qcustompluginmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustompluginmanager.o moc_qcustompluginmanager.cpp

moc_qcustomtabbarlineedit.o: moc_qcustomtabbarlineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomtabbarlineedit.o moc_qcustomtabbarlineedit.cpp

moc_qtplayer.o: moc_qtplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtplayer.o moc_qtplayer.cpp

moc_qcustomplugintest.o: moc_qcustomplugintest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplugintest.o moc_qcustomplugintest.cpp

moc_music-goear.o: moc_music-goear.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_music-goear.o moc_music-goear.cpp

moc_qtglobalshortcut.o: moc_qtglobalshortcut.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtglobalshortcut.o moc_qtglobalshortcut.cpp

moc_qtsingleapplication.o: moc_qtsingleapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtsingleapplication.o moc_qtsingleapplication.cpp

moc_qtlocalpeer.o: moc_qtlocalpeer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlocalpeer.o moc_qtlocalpeer.cpp

moc_qtgoear.o: moc_qtgoear.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtgoear.o moc_qtgoear.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

